### ISSUE TITLE
RM issue

### ISSUE THREAD

**Issue by m1r425** [The-Modding-Calculator/Easy-Vita-P4G-EBOOT-Patch#2]
C:\Users\Teehee\Downloads\MODEBOOTPATCH\Easy-Vita-P4G-EBOOT-Patch-main>rm .\tempElfFiles\base_eboot.elf
'rm' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Teehee\Downloads\MODEBOOTPATCH\Easy-Vita-P4G-EBOOT-Patch-main>rm .\tempElfFiles\modded_eboot.elf
'rm' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Teehee\Downloads\MODEBOOTPATCH\Easy-Vita-P4G-EBOOT-Patch-main>rm .\modded_eboot.bin
'rm' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Teehee\Downloads\MODEBOOTPATCH\Easy-Vita-P4G-EBOOT-Patch-main>.\PSVita-RE-Tools\vita-unmake-fself.exe .\eboot.bin
Using original elf header

C:\Users\Teehee\Downloads\MODEBOOTPATCH\Easy-Vita-P4G-EBOOT-Patch-main>mv .\eboot.bin.elf .\tempElfFiles\base_eboot.elf
'mv' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Teehee\Downloads\MODEBOOTPATCH\Easy-Vita-P4G-EBOOT-Patch-main>".\RPCS3PatchEboot - TGE\RPCS3PatchEboot.exe" ".\tempElfFiles\base_eboot.elf" ".\Patches - Lipsum\PCSE00120.yml" ".\tempElfFiles\modded_eboot.elf" -FilterByName p4g_ModSupport
Error: Exception thrown: Could not find a part of the path 'C:\Users\Teehee\Downloads\MODEBOOTPATCH\Easy-Vita-P4G-EBOOT-Patch-main\tempElfFiles\base_eboot.elf'.
Stacktrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at RPCS3PatchEboot.Program.TryGetBaseOffsetFromEBOOT(Int32& baseOffset)
   at RPCS3PatchEboot.Program.Main(String[] args)
Press any key to exit.

**Comment by The-Modding-Calculator** [comment]
Hello! I've just pushed a fix for this issue. Thanks for letting me know about.
I was a little but dumb and had linux commands such as rm and mv aliased on my PC and forgot about them. But I've fixed the scripts now and they use the correct del and move commands.

Please let me know if you have any more issue thanks
